name: GitHub PR Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  github-pr-check:
    runs-on: [self-hosted, acrgpu]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Step 0: Debug GITHUB_TOKEN (for you to verify it is present) ---
      - name: Validate GITHUB_TOKEN
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if (-not $env:GITHUB_TOKEN) {
            Write-Error "❌ GITHUB_TOKEN is empty—check that Actions are enabled and permissions are correct."
            exit 1
          }

          Write-Host "🔑 GITHUB_TOKEN loaded (length: $($env:GITHUB_TOKEN.Length) chars)"
          $preview = $env:GITHUB_TOKEN.Substring(0, 4) + "..." + $env:GITHUB_TOKEN.Substring($env:GITHUB_TOKEN.Length - 4)
          Write-Host "🔐 GITHUB_TOKEN (preview): $preview"

      # --- Step 1: Build PR context + call backend (uses GITHUB_TOKEN) ---
      - name: Call backend and save artifacts
        id: backend_call
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # GitHub PR context
          $prNumber   = "${{ github.event.pull_request.number }}"
          $repo       = "${{ github.repository }}"           # org/repo
          $repoOwner  = "${{ github.repository_owner }}"
          $repoName   = "${{ github.event.repository.name }}"
          $htmlUrl    = "${{ github.event.pull_request.html_url }}"
          $requester  = "${{ github.event.pull_request.user.login }}"
          $requesterEmail = "${{ github.event.pull_request.user.email }}"  # may be null

          if (-not $prNumber -or -not $repo -or -not $htmlUrl) {
            Write-Error "❌ Missing one of: prNumber, repo, htmlUrl."
            Write-Host "Values: prNumber=$prNumber, repo=$repo, htmlUrl=$htmlUrl"
            exit 1
          }

          Write-Host "🔎 PR context:"
          Write-Host "  Repo:        $repo"
          Write-Host "  PR number:   $prNumber"
          Write-Host "  PR URL:      $htmlUrl"
          Write-Host "  Requester:   $requester"

          # Use PR HTML URL as repo link
          $repoLink = $htmlUrl

          # Creator + reviewers
          $creatorLogin = "${{ github.event.pull_request.user.login }}"
          $creatorEmail = "${{ github.event.pull_request.user.email }}"
          if (-not $creatorEmail) {
            $creatorEmail = "$creatorLogin@github.local"
          }

          $reviewersLogins = @()
          $reviewersLogins += @(${{
            toJson(github.event.pull_request.requested_reviewers)
          }} | ConvertFrom-Json | ForEach-Object { $_.login })
          $reviewersLogins = $reviewersLogins | Sort-Object -Unique | Where-Object { $_ }

          $reviewersEmails = @()
          foreach ($r in $reviewersLogins) {
            $reviewersEmails += "$r@github.local"
          }

          $allEmails = @($creatorEmail) + $reviewersEmails
          $allEmails = $allEmails | Sort-Object -Unique | Where-Object { $_ -match '^[^@]+@[^@]+\.[^@]+$' }

          $joinedReviewers = $allEmails -join ','

          Write-Host "👤 Creator email: $creatorEmail"
          Write-Host "👥 Reviewer emails:"
          foreach ($e in $allEmails) { Write-Host "  • $e" }

          # Encode fields (spaces -> %20)
          $encodedRepoLink   = $repoLink  -replace ' ', '%20'
          $encodedToken      = $env:GITHUB_TOKEN
          $encodedRequester  = $requesterEmail -replace ' ', '%20'
          $encodedReviewers  = $joinedReviewers -replace ' ', '%20'
          $encodedCreator    = $creatorEmail -replace ' ', '%20'

          $backendUrl = 'https://10.98.0.97/api/review/github-pr/'
          Write-Host "📨 Sending PR details to backend at: $backendUrl"

          $result = & curl.exe -k -X POST -sS `
            -F "repo_link=$encodedRepoLink" `
            -F "githubpat=$encodedToken" `
            -F "r_effort=low" `
            -F "githubemail=$encodedRequester" `
            -F "prtype=active" `
            -F "reviewer_emails=$encodedReviewers" `
            -F "creator_email=$encodedCreator" `
            $backendUrl

          Write-Host "🌐 Raw backend response: $result"

          try {
            $json  = $result | ConvertFrom-Json
            $runId = $json.run_id
            if (-not $runId) {
              Write-Warning "⚠️ Missing run_id. Response:`n$result"
              exit 1
            }
          } catch {
            Write-Error "❌ JSON parse failed: $($_.Exception.Message)"
            exit 1
          }

          $artifactDir = "$env:GITHUB_WORKSPACE\artifacts"
          if (-not (Test-Path $artifactDir)) {
            New-Item -ItemType Directory -Path $artifactDir | Out-Null
          }

          Set-Content -Path "$artifactDir\run_id.txt"        -Value $runId
          Set-Content -Path "$artifactDir\creator_email.txt" -Value $creatorEmail
          $allEmails -join "`n" | Set-Content "$artifactDir\all_emails.txt"

          Write-Host "✅ Saved artifacts: run_id.txt, creator_email.txt, all_emails.txt"
          Write-Host "🎉 Review URL: https://10.98.0.97/#/github-pr/$runId/"

          Write-Output "run_id=$runId"            >> $env:GITHUB_OUTPUT
          Write-Output "artifactDir=$artifactDir" >> $env:GITHUB_OUTPUT

      # --- Step 2: PR comment using GITHUB_TOKEN (unchanged) ---
      - name: Post PR comment with review URL
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = `${{ steps.backend_call.outputs.run_id }}`;
            const reviewUrl = `https://10.98.0.97/#/github-pr/${runId}/`;
            const prNumber = context.payload.pull_request.number;

            const body = [
              "**Automated PR Review** is ready!",
              "",
              `View it here: ${reviewUrl}`
            ].join("\n");

            core.info(`Posting PR comment to #${prNumber} with review URL: ${reviewUrl}`);

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body
            });

      # --- Step 3: Email step (same as before, uses SMTP_USER/SMTP_PASS) ---
      - name: Send emails to creator + reviewers
        if: success()
        shell: pwsh
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          Write-Host "=== Step 1: Loading variables from artifacts ==="
          $artifactDir = "${{ steps.backend_call.outputs.artifactDir }}"
          if (-not $artifactDir) {
            $artifactDir = "$env:GITHUB_WORKSPACE\artifacts"
          }
          Write-Host "Artifact directory: $artifactDir"

          $creator   = Get-Content "$artifactDir\creator_email.txt" -Raw
          $rawEmails = Get-Content "$artifactDir\all_emails.txt" -Raw
          $runId     = Get-Content "$artifactDir\run_id.txt" -Raw
          $prId      = "${{ github.event.pull_request.number }}"

          Write-Host "Creator email loaded: $creator"
          Write-Host "Raw emails string loaded: '$rawEmails'"
          Write-Host "Run ID loaded: $runId"
          Write-Host "PR ID: $prId"

          Write-Host "`n=== Step 2: Validating SMTP environment variables ==="
          if (-not $env:SMTP_USER) {
            Write-Error "✖ SMTP_USER is not set; cannot send mail."
            exit 1
          } else {
            Write-Host "SMTP_USER exists: $env:SMTP_USER"
          }

          if (-not $env:SMTP_PASS) {
            Write-Error "✖ SMTP_PASS is not set; cannot authenticate."
            exit 1
          } else {
            Write-Host "SMTP_PASS is set (value hidden)"
          }

          Write-Host "`n=== Step 3: Splitting email list into array ==="
          $emails = $rawEmails -split '[,;\s]+' | Where-Object { $_ }
          Write-Host "Parsed email addresses:"
          foreach ($e in $emails) { Write-Host " • $e" }

          Write-Host "`n=== Step 4: Preparing SMTP credential object ==="
          $securePass = ConvertTo-SecureString $env:SMTP_PASS -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($env:SMTP_USER, $securePass)
          Write-Host "Credential object created for user $($cred.UserName)"

          Write-Host "`n=== Step 5: Building email subject and body ==="
          $frontendUrl = "https://10.98.0.97/#/github-pr/$runId/"
          Write-Host "Frontend URL: $frontendUrl"

          $subject = "Automated GitHub PR Review Link for PR #$prId"
          Write-Host "Email subject: $subject"

          $body = @"
Hi Team,

The automated code review has been completed for GitHub PR #$prId created by: $creator.

You can view the detailed results here:
$frontendUrl

Note: Please use Everi Gateway VPN.

Thanks,
DevOps Pipeline
"@
          Write-Host "Email body constructed."

          Write-Host "`n=== Step 6: Sending emails ==="
          $smtpServer = 'smtp.everi.com'
          $port       = 25
          Write-Host "SMTP server: $($smtpServer):$port"

          foreach ($email in $emails) {
            Write-Host "`n📨 Sending to $($email)..."
            try {
              Send-MailMessage `
                -To         $email `
                -From       $env:SMTP_USER `
                -Subject    $subject `
                -Body       $body `
                -SmtpServer $smtpServer `
                -Port       $port `
                -UseSsl     `
                -Credential $cred
              Write-Host "✔ Email successfully sent to $($email)"
            } catch {
              Write-Warning "⚠️ Failed sending to $($email): $($_.Exception.Message)"
            }
          }

          Write-Host "`nAll done."
