# ---
# name: PR Checker Workflow Template
# description: Runs internal checks on PR creation using org-wide acrgpu runner.
# icon: check-circle
# color: green
# ---
name: GitHub PR Checker
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  github-pr-check:
    runs-on: [self-hosted, acr]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Determine runner OS 
      - name: Detect runner OS
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "runner_os=$RUNNER_OS" >> $GITHUB_OUTPUT

      # --- Step 0: Debug GITHUB_TOKEN (bash version) ---
      - name: Validate GITHUB_TOKEN (bash)
        if: runner.os != 'Windows'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is empty—check that Actions are enabled and permissions are correct."
            exit 1
          fi

          echo "GITHUB_TOKEN loaded (length: ${#GITHUB_TOKEN} chars)"
          preview="${GITHUB_TOKEN:0:4}...${GITHUB_TOKEN: -4}"
          echo "GITHUB_TOKEN (preview): $preview"

      # --- Step 1: Build PR context + call backend (bash version) ---
      - name: Call backend and save artifacts (bash)
        id: backend_call_unix
        if: runner.os != 'Windows'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_HTML_URL: ${{ github.event.pull_request.html_url }}
          REQUESTER_LOGIN: ${{ github.event.pull_request.user.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.repository_owner }}
          CREATOR_LOGIN: ${{ github.event.pull_request.user.login }}
          CREATOR_EMAIL: ${{ github.event.pull_request.user.email }}
          REQUESTED_REVIEWERS: ${{ toJson(github.event.pull_request.requested_reviewers) }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          # Check required context variables
          if [ -z "$PR_NUMBER" ] || [ -z "$GITHUB_REPOSITORY" ] || [ -z "$PR_HTML_URL" ]; then
            echo "Missing one of: PR_NUMBER, GITHUB_REPOSITORY, PR_HTML_URL."
            echo "Values: PR_NUMBER=$PR_NUMBER, GITHUB_REPOSITORY=$GITHUB_REPOSITORY, PR_HTML_URL=$PR_HTML_URL"
            exit 1
          fi

          echo "🔎 PR context:"
          echo "  Repo:        $GITHUB_REPOSITORY"
          echo "  PR number:   $PR_NUMBER"
          echo "  PR URL:      $PR_HTML_URL"
          echo "  Requester:   $REQUESTER_LOGIN"

          repo_link="$PR_HTML_URL"

          creator_email="$CREATOR_EMAIL"
          if [ -z "$creator_email" ]; then
            creator_email="${CREATOR_LOGIN}"
          fi

          echo "Creator email: $creator_email"

          # Extract reviewer logins from JSON array
          reviewers_logins=$(echo "$REQUESTED_REVIEWERS" | jq -r '.[].login' 2>/dev/null | sort -u)
          if [ -z "$reviewers_logins" ]; then
            echo "Reviewer logins: None"
          else
            echo "Reviewer logins:"
            echo "$reviewers_logins" | while read -r reviewer; do
              echo "  • $reviewer"
            done
          fi

          # Encode fields by URL encoding spaces (%20), more encoding can be added if needed
          encoded_repo_link="${repo_link// /%20}"
          encoded_token="$GITHUB_TOKEN"
          encoded_creator_email="${creator_email// /%20}"
          encoded_creator_login="${CREATOR_LOGIN// /%20}"

          backend_url='https://10.98.0.97/api/review/git-pr/'
          echo "Sending PR details to backend at: $backend_url"

          # Send POST request with form data to backend
          result=$(curl -k -X POST -sS \
            -F "repo_link=$encoded_repo_link" \
            -F "triggerPat=$encoded_token" \
            -F "r_effort=low" \
            -F "email=$encoded_creator_email" \
            -F "gitUser=$encoded_creator_login" \
            -F "prtype=active" \
            "$backend_url")

          echo "Raw backend response: $result"
          
          # Parse JSON response with debug output
          run_id=$(echo "$result" | jq -r '.run_id' 2>/dev/null)
          echo "Parsed run_id: $run_id"
          
          creator=$(echo "$result" | jq -r '.prs.developer' 2>/dev/null)
          echo "Parsed creator: $creator"
          
          # Parse reviewers safely; if empty or null, set a default message
          reviewers=$(echo "$result" | jq -r '.prs.reviewers | join("\n")' 2>/dev/null)
          if [ -z "$reviewers" ] || [ "$reviewers" = "null" ]; then
            echo "No reviewers field found or empty in JSON."
            reviewers="No reviewers found"
          else
            echo "Parsed reviewers:"
            echo "$reviewers"
          fi
          
          # Validate run_id presence
          if [ -z "$run_id" ] || [ "$run_id" = "null" ]; then
            echo " Missing run_id. Response:"
            echo "$result"
            exit 1
          fi

          artifact_dir="$GITHUB_WORKSPACE/artifacts"
          mkdir -p "$artifact_dir"

          echo "$run_id" > "$artifact_dir/run_id.txt"
          echo "$creator" > "$artifact_dir/creator.txt"
          echo "$reviewers" > "$artifact_dir/all_reviewers.txt"

          echo "Saved artifacts: run_id.txt, creator.txt, all_reviewers.txt"
          echo "Review URL: https://10.98.0.97/#/pr-review/$run_id/"

          echo "run_id=$run_id" >> $GITHUB_OUTPUT
          echo "artifactDir=$artifact_dir" >> $GITHUB_OUTPUT

      # --- Step 2: Enhanced PR comment with mentions + creator (bash) ---
      - name: Post PR comment with review URL and mentions (bash)
        if: success() && runner.os != 'Windows'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const artifactDir = '${{ steps.backend_call_unix.outputs.artifactDir }}';
            
            // Read reviewers and creator from artifacts
            const reviewersRaw = fs.readFileSync(`${artifactDir}/all_reviewers.txt`, 'utf8').trim();
            const reviewers = reviewersRaw ? reviewersRaw.split('\n').filter(r => r.trim()) : [];
            
            const creatorRaw = fs.readFileSync(`${artifactDir}/creator.txt`, 'utf8').trim();
            const creator = creatorRaw && creatorRaw !== 'null' ? creatorRaw : 'Unknown';
            
            const runId = '${{ steps.backend_call_unix.outputs.run_id }}';
            const reviewUrl = `https://10.98.0.97/#/pr-review/${runId}/`;
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
      
            // Reviewer mentions
            const reviewerMentions = reviewers.length > 0 
              ? reviewers.map(r => `**@${r}**`).join(' ') 
              : '**No reviewers assigned**';
      
            const body = [
              reviewerMentions,
              "",
              "**Automated PR Review Ready!**",
              "",
              `👥 **Created by:** ${creator}`,
              `**PR Number:** #${prNumber}`,
              `**Repo Name:** ${repo}`,
              `🔗 **Review Link:** ${reviewUrl}`,
              "",
              "Please review the automated analysis and provide feedback!"
            ].join("\n");
      
            core.info(`Posting enhanced PR comment to #${prNumber} - Creator: ${creator}, Reviewers: ${reviewers.length}`);
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body
            });

      # -- Step 0: Validate GITHUB_TOKEN (PowerShell)
      - name: Validate GITHUB_TOKEN (PowerShell)
        if: runner.os == 'Windows'
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $token = $env:GITHUB_TOKEN
          if ([string]::IsNullOrWhiteSpace($token)) {
            Write-Error "GITHUB_TOKEN is empty - check that Actions are enabled and permissions are correct."
            exit 1
          }
          
          $len = $token.Length
          Write-Host ("GITHUB_TOKEN loaded (length: {0} chars)" -f $len)
          
          if ($len -ge 8) {
            $preview = $token.Substring(0,4) + '...' + $token.Substring($len - 4, 4)
          } else {
            $preview = $token
          }
          
          Write-Host ("GITHUB_TOKEN (preview): {0}" -f $preview)


      # --- Step 1: Build PR context + call backend (PowerShell version) ---
      - name: Call backend and save artifacts (PowerShell)
        id: backend_call_windows
        if: runner.os == 'Windows'
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_HTML_URL: ${{ github.event.pull_request.html_url }}
          REQUESTER_LOGIN: ${{ github.event.pull_request.user.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.repository_owner }}
          CREATOR_LOGIN: ${{ github.event.pull_request.user.login }}
          CREATOR_EMAIL: ${{ github.event.pull_request.user.email }}
          REQUESTED_REVIEWERS: ${{ toJson(github.event.pull_request.requested_reviewers) }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          # Optional: ignore invalid/self-signed certs (mirror of curl -k)
          try {
            [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
          } catch {
            # may not be supported everywhere; ignore
          }
          
          if (-not $env:PR_NUMBER -or -not $env:GITHUB_REPOSITORY -or -not $env:PR_HTML_URL) {
            Write-Error "Missing one of: PR_NUMBER, GITHUB_REPOSITORY, PR_HTML_URL."
            Write-Host ("Values: PR_NUMBER={0}, GITHUB_REPOSITORY={1}, PR_HTML_URL={2}" -f $env:PR_NUMBER, $env:GITHUB_REPOSITORY, $env:PR_HTML_URL)
            exit 1
          }
          
          Write-Host "PR context:"
          Write-Host ("  Repo:      {0}" -f $env:GITHUB_REPOSITORY)
          Write-Host ("  PR number: {0}" -f $env:PR_NUMBER)
          Write-Host ("  PR URL:    {0}" -f $env:PR_HTML_URL)
          Write-Host ("  Requester: {0}" -f $env:REQUESTER_LOGIN)
          
          $repo_link = $env:PR_HTML_URL
          
          $creator_email = $env:CREATOR_EMAIL
          if ([string]::IsNullOrWhiteSpace($creator_email)) {
            $creator_email = $env:CREATOR_LOGIN
          }
          Write-Host ("Creator email: {0}" -f $creator_email)
          
          # Parse requested reviewers JSON if present
          $reviewers_logins = @()
          if (-not [string]::IsNullOrWhiteSpace($env:REQUESTED_REVIEWERS)) {
            try {
              $requested = $env:REQUESTED_REVIEWERS | ConvertFrom-Json -ErrorAction Stop
              if ($requested -is [System.Array]) {
                $reviewers_logins = $requested | ForEach-Object { $_.login } | Sort-Object -Unique
              } elseif ($requested -ne $null -and $requested.login) {
                $reviewers_logins = @($requested.login)
              }
            } catch {
              Write-Warning ("Failed to parse REQUESTED_REVIEWERS JSON: {0}" -f $_)
            }
          }
          
          if ($reviewers_logins.Count -eq 0) {
            Write-Host "Reviewer logins: None"
          } else {
            Write-Host "Reviewer logins:"
            $reviewers_logins | ForEach-Object { Write-Host ("  • {0}" -f $_) }
          }
          
          # Basic URL-encoding for spaces (adapt if you need full encoding)
          $encoded_repo_link = $repo_link -replace ' ', '%20'
          $encoded_token = $env:GITHUB_TOKEN
          $encoded_creator_email = $creator_email -replace ' ', '%20'
          $encoded_creator_login = $env:CREATOR_LOGIN -replace ' ', '%20'
          
          $backend_url = 'https://10.98.0.97/api/review/git-pr/'
          Write-Host ("Sending PR details to backend at: {0}" -f $backend_url)
      
          # ---- Build proper multipart/form-data body with boundary (text-only parts) ----
          $boundary = [guid]::NewGuid().ToString()
          $lf = "`r`n"
      
          $bodyLines = @(
            "--$boundary",
            "Content-Disposition: form-data; name=`"repo_link`"",
            "",
            $encoded_repo_link,
            "--$boundary",
            "Content-Disposition: form-data; name=`"prtype`"",
            "",
            "active",
            "--$boundary",
            "Content-Disposition: form-data; name=`"r_effort`"",
            "",
            "low",
            "--$boundary",
            "Content-Disposition: form-data; name=`"gitUser`"",
            "",
            $encoded_creator_login,
            "--$boundary",
            "Content-Disposition: form-data; name=`"email`"",
            "",
            $encoded_creator_email,
            "--$boundary",
            "Content-Disposition: form-data; name=`"triggerPat`"",
            "",
            $encoded_token,
            "--$boundary--",
            ""
          ) -join $lf
      
          $contentType = ("multipart/form-data; boundary={0}" -f $boundary)
          
          try {
            $response = Invoke-RestMethod -Uri $backend_url -Method Post -Body $bodyLines -ContentType $contentType
          } catch {
            Write-Error ("Backend POST failed: {0}" -f $_)
            exit 1
          }
          
          $raw = $response | ConvertTo-Json -Depth 10
          Write-Host ("Raw backend response: {0}" -f $raw)
          
          # Parse run_id, creator and reviewers from returned object (handles null/missing)
          $run_id = $null
          $creator = $null
          $reviewers = @()
          
          if ($response -ne $null) {
            if ($response.run_id) { $run_id = $response.run_id }
            if ($response.prs -ne $null) {
              if ($response.prs.developer) { $creator = $response.prs.developer }
              if ($response.prs.reviewers) {
                if ($response.prs.reviewers -is [System.Array]) {
                  $reviewers = $response.prs.reviewers
                } else {
                  $reviewers = @($response.prs.reviewers)
                }
              }
            }
          }
          
          Write-Host ("Parsed run_id: {0}" -f $run_id)
          Write-Host ("Parsed creator: {0}" -f $creator)
          if ($reviewers.Count -eq 0) {
            Write-Host "No reviewers field found or empty in JSON."
          } else {
            Write-Host "Parsed reviewers:"
            $reviewers | ForEach-Object { Write-Host ("  • {0}" -f $_) }
          }
          
          if (-not $run_id) {
            Write-Error "Missing run_id. Response:"
            Write-Host $raw
            exit 1
          }
          
          $artifact_dir = Join-Path $env:GITHUB_WORKSPACE 'artifacts'
          New-Item -ItemType Directory -Path $artifact_dir -Force | Out-Null
          
          # Save artifacts
          $run_id | Out-File -FilePath (Join-Path $artifact_dir 'run_id.txt') -Encoding utf8
          
          $creator_for_file = if ($creator -ne $null) { $creator } else { '' }
          $creator_for_file | Out-File -FilePath (Join-Path $artifact_dir 'creator.txt') -Encoding utf8
          
          if ($reviewers.Count -gt 0) {
            $reviewers -join "`n" | Out-File -FilePath (Join-Path $artifact_dir 'all_reviewers.txt') -Encoding utf8
          } else {
            "No reviewers found" | Out-File -FilePath (Join-Path $artifact_dir 'all_reviewers.txt') -Encoding utf8
          }
          
          Write-Host "Saved artifacts: run_id.txt, creator.txt, all_reviewers.txt"
          Write-Host ("Review URL: https://10.98.0.97/#/pr-review/{0}/" -f $run_id)
          
          # Export outputs to GitHub Actions
          Add-Content -Path $env:GITHUB_OUTPUT -Value ("run_id={0}" -f $run_id)
          Add-Content -Path $env:GITHUB_OUTPUT -Value ("artifactDir={0}" -f $artifact_dir)


      # --- Step 2: Enhanced PR comment with mentions + creator (PowerShell) ---
      - name: Post PR comment with review URL and mentions (PowerShell)
        if: success() && runner.os == 'Windows'
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          $artifactDir = "${{ steps.backend_call_windows.outputs.artifactDir }}"
          if (-not (Test-Path $artifactDir)) {
            Write-Error ("Artifact dir not found: {0}" -f $artifactDir)
            exit 1
          }
          
          $reviewersRaw = Get-Content -Path (Join-Path $artifactDir 'all_reviewers.txt') -ErrorAction SilentlyContinue -Raw
          $reviewersRaw = $reviewersRaw.Trim()
          $reviewers = @()
          if (-not [string]::IsNullOrWhiteSpace($reviewersRaw) -and $reviewersRaw -ne 'No reviewers found') {
            $reviewers = $reviewersRaw -split "(`r?`n)|(`n)" | Where-Object { $_.Trim().Length -gt 0 }
          }
          
          $creatorRaw = (Get-Content -Path (Join-Path $artifactDir 'creator.txt') -ErrorAction SilentlyContinue -Raw).Trim()
          $creator = if ($creatorRaw -and $creatorRaw -ne 'null') { $creatorRaw } else { 'Unknown' }
          
          $runId = '${{ steps.backend_call_windows.outputs.run_id }}'
          $reviewUrl = ("https://10.98.0.97/#/pr-review/{0}/" -f $runId)
          $prNumber = $env:PR_NUMBER
          $parts = $env:GITHUB_REPOSITORY.Split('/')
          $owner = $parts[0]
          $repo = $parts[1]
          
          if ($reviewers.Count -gt 0) {
            $reviewerMentions = ($reviewers | ForEach-Object { ("**@{0}**" -f $_) }) -join ' '
          } else {
            $reviewerMentions = '**No reviewers assigned**'
          }
          
          $bodyLines = @(
            $reviewerMentions
            ""
            "**Automated PR Review Ready!**"
            ""
            ("**Created by:** {0}" -f $creator)
            ("**PR Number:** #{0}" -f $prNumber)
            ("**Repo Name:** {0}" -f $repo)
            ("**Review Link:** {0}" -f $reviewUrl)
            ""
            "Please review the automated analysis and provide feedback!"
          )
          $body = $bodyLines -join "`n"
          
          Write-Host ("Posting enhanced PR comment to #{0} - Creator: {1}, Reviewers: {2}" -f $prNumber, $creator, $reviewers.Count)
          
          # Post comment via GitHub REST API
          $url = ("https://api.github.com/repos/{0}/{1}/issues/{2}/comments" -f $owner, $repo, $prNumber)
          $headers = @{
            Authorization = ("Bearer {0}" -f $env:GITHUB_TOKEN)
            Accept        = "application/vnd.github+json"
            'User-Agent'  = 'PowerShell-Invoke'
          }
          $payload = @{ body = $body } | ConvertTo-Json -Depth 5
          
          try {
            Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $payload -ContentType 'application/json'
            Write-Host "Comment posted."
          } catch {
            Write-Error ("Failed to post comment: {0}" -f $_)
            exit 1
          }
